language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install unittest2
  - pip install Flask
  - pip install flask_testing
# command to run tests
script: python test.py